default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: instapp_development

test:
  <<: *default
  database: instapp_test

production:
  <<: *default
  database: instapp_production
  username: instapp
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
